resolver: lts-5.1

packages:
- 'clash-lib'
- 'clash-verilog'
- 'clash-systemverilog'
- 'clash-vhdl'
- 'clash-ghc'
- 'testsuite'
- location:
    git: https://github.com/clash-lang/clash-prelude.git
    commit: de99763cfd91d28af753942c6ba6f0e3b4dbe298
- location:
    git: https://github.com/clash-lang/ghc-typelits-natnormalise.git
    commit: 914cda2d25dc18f8a6d9ce0d88f34fc498085ff9
